services:
  - type: web
    name: telegram-bot-WormGPT
    env: python
    plan: free
    buildCommand: |
      pyenv install 3.11.9 -s
      pyenv global 3.11.9
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SERVICE_API_KEY
        sync: false
      - key: SERVICE_ENDPOINT
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: DB_PATH
        sync: false
